spring:
  security:
    user:
      password: 1
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/Coding/SpringNote/SpringNote/security
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug